name: ♻️ Reusable CI

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        required: false
        default: '20'
    secrets: {}

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}

      - run: npm ci
      - run: npm run lint:check
      - run: npm run test
      - run: npm run coverage-badge
      - run: npm run prepare
      - uses: actions/upload-artifact@v6
        with:
          name: dist
          path: dist/
