name: ♻️ Reusable CI

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        required: false
        default: '20'
    secrets: 
      CODECOV_TOKEN: # For code coverage uploads
        required: false

jobs:
  test-build-report:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint:check

      - name: Run tests
        run: npm run test

      - name: Generate coverage badge
        run: npm run coverage-badge

      - name: Upload coverage to Codecov
        if: ${{ secrets.CODECOV_TOKEN }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          flags: unittests

      - name: Build with ncc
        run: npm run prepare

      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          name: dist
          path: dist/
